language: java

before_install:
- chmod +x gradlew

jdk:
- openjdk8

branches:
  only:
  - master

# Travis CI 서버의 Home
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
- zip -r noteboook_webservice *
- mkdir -p deploy
#- mv noteboook_webservice.zip deploy/noteboook_webservice.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: notebookwebservice
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
    repo: l10032503/notebook_webservice
    branch: master

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: notebookwebservice
  key: noteboook_webservice.zip
  bundle_type: zip
  application: noteboook_webservice
  deployment_group: noteboook_webservice_group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    repo: l10032503/notebook_webservice
    branch: master


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
    - l10032503@gmail.com