spring:
  datasource:
      url: jdbc:mariadb://notebookwebservice.cjmajxgzxql6.ap-northeast-2.rds.amazonaws.com:3306/notebookdata
      username: l10032503
      password: 20192019
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  data:
    web:
      pageable:
        one-indexed-parameters: true